---
spring:
  database1:
    port: 33006
    username: root
    password: root
  database1:
    port: 33006
    username: root
    password: root
    
---
spring:
  database1:
    port: 33006
    username: root
    password: root
  database1:
    port: 33006
    username: root
    password: root
  
